### ISSUE TITLE
pose estimate

### ISSUE THREAD

**Issue by songminglong** [patrikhuber/superviseddescent#10]
@patrikhuber , hi , I want to know that how do you get 3-d face coordinates of "Mat facemodel;"(in pose_estimation.cpp), and three angles(pitch,yaw,roll) of "Mat predicted_params" are relative to given 3-d face, is it right?

**Comment by patrikhuber** [comment]
@shangguanxiaohu Hi,
The face coordinates in the example are just from our internal 3D model, but you can use any face mesh basically. We are actually planning to release our 3D model stuff too, in the next few weeks.
The angles are in a coordinate system however you choose to learn it at training-time. So yes, you can see it as relative to the 3D face.

**Comment by songminglong** [comment]
I think given 3-d face should be more frontal, and there are so many parameters of the model(eg. focalLength, tz and other params) that may reduce the stability of the model. Actually, I have trained the  pose estimation model use your given faceModel data, and found that estimated angles have large changes in test(I have normalize landmarks to the center(500,500)).

**Comment by patrikhuber** [comment]
What do you mean with _"given 3-d face should be more frontal"_? It should be frontal - is it not?
If you fix the focal length (i.e. assuming an affine camera model, if you set it large), there's 6 parameters. I don't think that's very much? I would say, try with a fixed focal length, and then go from there!

**Comment by patrikhuber** [comment]
I'm going to close this, we can always reopen the issue if you have more questions or problems.
