### ISSUE TITLE
Missing verbose_solver.hpp

### ISSUE THREAD

**Issue by rex-yue-wu** [patrikhuber/superviseddescent#12]
Hi Patrik,

It seems that include/verbose_solver.hpp file is missing. I am not sure whether this file is needed in the current version, but basically I cannot compile your project as it is. 

Many thanks,

**Comment by patrikhuber** [comment]
Hi @rex-yue-wu,

You're right, thank you very much for spotting and reporting that! I just added the file along with one or two other minor changes. (fix in 2f85b13)

Thanks!

**Comment by patrikhuber** [comment]
Fixed and released as [v0.4.1](https://github.com/patrikhuber/superviseddescent/releases/tag/v0.4.1). Let me know if you have any more issues :-)

**Comment by rex-yue-wu** [comment]
Thanks for your quick response.
