### ISSUE TITLE
Training headpose with multiple models

### ISSUE THREAD

**Issue by axeper** [patrikhuber/superviseddescent#13]
Hi,

I successfully adapted pose_estimation for one of our 3D models.
Now I would like to be able to train on more than one model but I am having trouble modifying the code.
How should I proceed to adapt the ModelProjection variable for training and testing?

Cheers

**Comment by patrikhuber** [comment]
Hi @axeper,

Glad to hear you were successful!
I'm not sure I understand your question. How would you like to train on more than one model? More than one 3D model?

Cheers,
Patrik

**Comment by axeper** [comment]
I wanted to know if it was possible to train with more than one facemodel. That would mean for instance to be able to train the regressors with, let's say, one male model and one female model. I thought it would increase the testing accuracy, wouldn't it?

**Comment by patrikhuber** [comment]
Hmm, I'm not that sure that what you're trying to do makes sense. From a software-perspective, yes, I would adapt `ModelProjection` to contain both face models, and then in the projection, you could do whatever you want with the first model, and then do whatever else you want with the second model.

**Comment by axeper** [comment]
Right, 
Let me explain what I'm trying to do: I'm trying to make the code as generic as possible (i.e. obtaining high accuracy predictions for a high number of different models) . For this purpose, I thought that training the regressors on multiple 3D models at the same time would increase the robustness while testing.

However, from your answers, I get the impression that it is not possible to train with more than one model. 

Then, in the case where I have one female model and one male model, is it better in your opinion to take the mean of each landmarks in order to obtain a mean 3D model or to adapt the code for male models only or females models only? Or would you suggest doing something else?

Thanks a lot for the quick answers, it is really appreciated.

**Comment by patrikhuber** [comment]
I see. I think that should be quite easy actually. I'm not sure where you got the impression from that it would not be possible to train with multiple models (I don't think I said anything like that :-) ) - it's quite straightforward to just add multiple models to `ModelProjection`, and this should do what you want to do.

Regarding your second question: I guess at some point you need to merge "something", don't you? Let's say you have a male and a female model, and both predict a parameter update. How do you go from there? Will you decide between them, or pick the average?

**Comment by patrikhuber** [comment]
Feel free to re-open if you're still working on it and have any further issues.
