### ISSUE TITLE
run under Visual Studio 2013

### ISSUE THREAD

**Issue by mydude** [patrikhuber/superviseddescent#22]
hi patrikhuber
    thank you for your code. I'm following your code and work, could you mind send me a copy of Visual Studio 2013 of this project?

**Comment by mydude** [comment]
my email:  wyw636@163.com  thanks!

**Comment by patrikhuber** [comment]
Hi,
If you mean a Visual Studio solution file, then, that is what CMake generates for you. Follow the build instructions, and the call to `cmake` will generate a `.sln` file.

**Comment by mydude** [comment]
nice!  thank you very much!
