### ISSUE TITLE
building error with VS2012

### ISSUE THREAD

**Issue by musicfish1973** [patrikhuber/superviseddescent#23]
superviseddescent-master\include\superviseddescent/utils/ThreadPool.h(49): error C2332: “class”: 缺少标记名
superviseddescent-master\include\superviseddescent/utils/ThreadPool.h(49): error C2011: “<unnamed-tag>”:“enum”类型重定义
1>          D:\Microsoft Visual Studio 11.0\VC\include\thr/xthreads.h(41) : 参见“<unnamed-tag>”的声明
superviseddescent-master\include\superviseddescent/utils/ThreadPool.h(49): error C2143: 语法错误 : 缺少“,”(在“...”的前面)

**Comment by patrikhuber** [comment]
Hi, sorry about the late reply, I didn't see the GitHub notification.

VS2012 has a really outdated compiler and is not supported. Please upgrade to 2015.

If you wanted, I'm sure you could make it work with VS2012 with minor modifications, but you'd have to do that yourself - this project uses modern C++11/14 :-)
