### ISSUE TITLE
How can I convert code to client web based code

### ISSUE THREAD

**Issue by Sun1718** [patrikhuber/superviseddescent#26]
Dear Patrik

I want to use facial landmark detection in web based application. How can I convert code to client side web based code. face_landmarks_model_rcr_68.bin is about 85M and it is heavy to load in web applications. How can I use it?

Regards.
Morteza

**Comment by patrikhuber** [comment]
Hi Morteza,

That's a good question. You could decrease the size to around half or a bit less by using 1-2 fewer cascades, which would decrease performance just a little bit. Maybe you can keep the regressor server-side? Probably not an option though.

Another idea would be to compress the file using LZMA compression or something similar which is fast. You could try how small it gets.

I don't have another idea right now from the top of my head, I'd need to think about it.

**Comment by Sun1718** [comment]
Thanks for your quick reply,

I've compressed it with LZMA and size decreased to about 75M. but it is heavy still. 

About using 1-2 less cascades, 40M is also heavy for us.

About keeping regressor in server-side, I think it is not feasible. because we must move each frame to server for processing and it is not real time.

About convert code to web based code, I study about Emscripten. It can convert c++ to javascript, but I don't try it. do you know about it?

thanks again.

**Comment by ghost** [comment]
maybe you can try other face landmark detection method, and you can try '3000fps' code in github

**Comment by Sun1718** [comment]
Thanks for your reply.

Regards,
Morteza
