### ISSUE TITLE
facial landmark tracking

### ISSUE THREAD

**Issue by Hardold** [patrikhuber/superviseddescent#30]
Hi,
   Do this  approach allow for real-time landmark tracking in videos?  Does this program has one  function for facial landmark detection and tracking ? I want to track the landmark .What should I do ?Do I need to write the tracking function myself?

**Comment by patrikhuber** [comment]
Hi,
Sure it allows real-time landmark tracking. You're right, I noticed the code of [apps/rcr/rcr-track.cpp](https://github.com/patrikhuber/superviseddescent/blob/master/apps/rcr/rcr-track.cpp) is a bit outdated, it does only detection, not tracking. However, there is an overload of the detect() function available, that takes the landmarks of the previous frames as input, and with these, we do tracking. You can have a look at how we do it in [the 4dface app](https://github.com/patrikhuber/4dface/blob/master/apps/4dface.cpp#L169-L195).

Of course if you wanted to, you could do a lot smarter stuff by yourself, I'd probably derive from [`detection_model`](https://github.com/patrikhuber/superviseddescent/blob/master/include/rcr/model.hpp#L121) and then add some state to the class.

**Comment by Hardold** [comment]
Oh, thinks  a lot !

**Comment by patrikhuber** [comment]
I'll close this, feel free to reopen if you have further questions!

**Comment by Hardold** [comment]
ok
