### ISSUE TITLE
Speed of the facial landmark detection on a phone

### ISSUE THREAD

**Issue by Hardold** [patrikhuber/superviseddescent#31]
I transplanted your program to the phone and found that  facial landmark detection of the speed is very slow.On a 640*480 image, the processing time is about 450ms( not include the time to find the face).How can I speed up ? Where is the problem ?

**Comment by patrikhuber** [comment]
450ms seems a bit slow. The answer to

> How can I speed up ? Where is the problem ?

is always: Run the profiler. Nobody else can tell you.

That aside, you can gain speed by using/training a model with a fewer number of regressors (4 or so), less landmarks, the HOG feature extraction could be parallelised, or you could use faster features altogether (maybe LBP or something like that?).

**Comment by Hardold** [comment]
Thank you for your reply.
