### ISSUE TITLE
Minimize Landmark detection Jitter

### ISSUE THREAD

**Issue by Larumbergera** [patrikhuber/superviseddescent#34]
Hi Patrik,

I have run a landmark detection with your pre-trained model "face_landmarks_model_rcr_68.bin" to a Still Face video (done synthetically) and I have seen that in each frame, the Landmarks' position is different. I want to minimize the diference between frames.

I think detect landmarks 'x' times and average each frame should minimize jitter.

So, what do yo think about this solution? Do you think there is a better way to minimize it?
Is it possible to train a model with less jitter?

Regards,

Andoni.

**Comment by patrikhuber** [comment]
Hi,

I think that usually people just smooth the detections, i.e. a moving, weighted average or something like that. Every landmark detection/tracking algorithm I've seen so far has jitter, even commercial ones, and most use some kind of smoothing, as far as I am aware, so the jitter is reduced/gone in the end result (at the cost of a slight latency).

**Comment by Larumbergera** [comment]
Thanks a lot!
