### ISSUE TITLE
which dataset was used for pre-trained "face_landmarks_model_rcr_68.bin" model.

### ISSUE THREAD

**Issue by gp1313** [patrikhuber/superviseddescent#35]

**Comment by patrikhuber** [comment]
It's trained on ibug-lfpw, ibug, ibug-afw, and ibug-helen-tr.

**Comment by gp1313** [comment]
Thanks.
PS- Your work is inspiring at least :)

**Comment by Larumbergera** [comment]
Hi,

sorry to bother you again with this but, can you upload the program used to train face_landmarks_model_rcr_68.bin?

I know there is an example (rcr-train) but it uses a mean_landmarks calculated only from ibug-lfpw.

Regards,

Andoni.

**Comment by patrikhuber** [comment]
Hi Andoni,

I'm quite sure some people asked that before and I uploaded the code and parameters to GitHub, I think it's in one of the (most likely closed) GitHub issues. Can you have a look please?

Thanks,
Patrik

**Comment by Larumbergera** [comment]
Yes, I've found it [here](https://github.com/patrikhuber/superviseddescent/issues/28).

Thanks,
Andoni.

**Comment by patrikhuber** [comment]
Great! :-)
