### ISSUE TITLE
rcr-train issue: No such file or directory

### ISSUE THREAD

**Issue by Krzef** [patrikhuber/superviseddescent#36]
Hi Patrik,

I've tried to run rcr-train to prepare a model for tests.
Unfortunately, it's not working. Prints the residual but also got this msg:
```
boost::filesystem::directory_iterator::construct: No such file or directory: "home/user/superviseddescent/examples/data/ibug_lfpw_trainset/"
```
Given arguments are below:
```
--data "/home/user/superviseddescent/examples/data/ibug_lfpw_trainset/"  
--mean "/home/user/superviseddescent/examples/data/mean_ibug_lfpw_68.txt"   
--facedetector "/home/user/opencv_files/haarcascade_frontalface_alt.xml"   
--config "/home/user/superviseddescent/apps/rcr/data/rcr_training_22.cfg"   
--evaluation "/home/user/superviseddescent/apps/rcr/data/rcr_eval.cfg"   
--output "/home/user/superviseddescent/apps/rcr/trained_output_model.bin"   
--test-data "home/user/superviseddescent/examples/data/ibug_lfpw_trainset/" 
```
if I choose one pic (as below), the result is the same
```
--test-data "home/user/superviseddescent/examples/data/ibug_lfpw_trainset/image_0002.png" 
```
Do you know where I can find the source of this issue?
Thanks in advance for your time!

**Comment by patrikhuber** [comment]
Hi,

You'll have to debug this one, I haven't used `rcr-train` in a while. Just step through it in the debugger, and you'll see what's wrong, it's easy enough. Probably the path needs to be given in a different way or something like that. Maybe just without the final `/`.

**Comment by patrikhuber** [comment]
I'm going to assume this was a user mistake and you resolved it?

**Comment by Krzef** [comment]
Yes, you're right, sorry for no update from my side.
