### ISSUE TITLE
Question about inter eye distance (IEM)

### ISSUE THREAD

**Issue by Krzef** [patrikhuber/superviseddescent#37]
Hi Patrik,

I want to ask about rcr-train and rcr-detect files.
Algorithm calculates inter eye distance, understand that it's needed to better calculate eye landmarks.
But if it's really required to use IEM to train model in rcr-train? For example, I only want to detect nose or mouth to get better speed but don't know if I can easily rebuild rcr-train without using IEM functions.
To sum up, I want to ask:
If inter eye distance is needed ONLY to calculate eye landmarks or whole algorithm depends on that(in some way)?

Thank you in advance for your time.

**Comment by patrikhuber** [comment]
The IED is not used to better calculate eye landmarks. It's for computing a resolution/size-independent shape update. So basically you want to compute the shape update relative to the current face size, and not in some arbitrary absolute units (e.g. pixels). See our RCRC paper for more details.
