### ISSUE TITLE
Question about "data/rcr/face_landmarks_model_rcr_22.bin"

### ISSUE THREAD

**Issue by xkx0430** [patrikhuber/superviseddescent#38]
Hi Patrik,

I want to ask data/rcr/face_landmarks_model_rcr_22.bin.
The algorithm uses only 22 key points to compute the regression and predicts 68 key points. I have tried to train the 68 feature points directly, and the result is not very good. Can you tell me why? Is it because of the regress's regularization parameter lamda?

Thanks a lot.

**Comment by patrikhuber** [comment]
Hi,

Please see #35, #28 for how I trained my 68 point model. The result is quite good (state of the art in 2014/2015 or so), nowadays there are better models but it's still very usable, and I'm sure it can be made better with more pose training data.

Thanks.

**Comment by Larumbergera** [comment]
Hi,

Could you tell me which ones are better?

Regards,

Andoni.

**Comment by patrikhuber** [comment]
I suggest you look at any CVPR 2016 papers or CVPR 2017 submissions. We also submitted one, see [here](https://arxiv.org/abs/1611.05396).

**Comment by Larumbergera** [comment]
Thanks!

**Comment by xkx0430** [comment]
Thanks! I got it.
