### ISSUE TITLE
 facial landmark points from a video file

### ISSUE THREAD

**Issue by sarmadm** [patrikhuber/superviseddescent#39]
Hi

Can I use superviseddescent  to save facial landmark points from a video file ?

**Comment by patrikhuber** [comment]
Sure!

**Comment by sarmadm** [comment]
What I need to do for this ?

**Comment by patrikhuber** [comment]
See rcr-track for a tracking example.
Please leave the GitHub Issues for actual programming issues with the code, and not for help on how to do simple programming. Thanks.
