### ISSUE TITLE
Purpose of post estimation and simple function in superviseddescent

### ISSUE THREAD

**Issue by wiliamc** [patrikhuber/superviseddescent#4]
Hi Patrik,

I builded the code and generated executable files for landmarkdetection, poseestimation and simplefunction

Can you please tell me the usage of poseestimation.cpp and simplefunction.cpp and how to execute the files

Landmark Detection:
I gave the inputs and got the output with some points drawn on the image.

Pose Estimation:
when i run these, getting residual points alone

For, Simple function no idea about that.

**Comment by patrikhuber** [comment]
Hi cibin91,

I strongly suggest you read the paper by the original authors, [Supervised Descent Method for Solving Nonlinear Least Squares Problems in Computer Vision](http://arxiv.org/abs/1405.0601). As you can read in the [README.md](https://github.com/patrikhuber/superviseddescent), the library implements a learning-based approach to certain vision (and possibly other) problems. One of the most popular use cases is facial landmark detection. The examples provided are deliberately short "hello world" examples. If you're interested in landmark detection, I'm in the process of making our full pre-trained model available.

Another application where we use a setup a bit similar to the pose estimation example given here is described in our paper [Fitting 3D Morphable Models using Local Features](http://arxiv.org/abs/1503.02330).

I think in your case, you first need to think about what you want to do, and then start from there.

Hope that helps,

Patrik

**Comment by patrikhuber** [comment]
I'm going to close this, as the documentation and the paper should explain most. Feel free to come back with any specific questions or problems.

If you're just interested in running landmark detection, have a look at my latest post in #3.
