### ISSUE TITLE
eigen function runs very slow

### ISSUE THREAD

**Issue by ardeal** [patrikhuber/superviseddescent#41]
Hi Prof.,
I run your code to train the model.
however, when I run the funtion solve in VerbosePartialPivLUSolver class, the following code runs very slow:

RowMajorMatrixXf AtA_Eigen = A_Eigen.transpose() * A_Eigen;

A_Eigen matxi is 20*8801.
it means that to do the transpose of matrix it needs 76588ms which is a very big value.
my system configurations are:
windowns10, CPU Intel i5-6200U, RAM 8G.

the QR of matrix cannot be finished at all in the solve function.

Do you have any idea about this issue?

**Comment by ardeal** [comment]
Hi Patrikhuber
I just now confirmed that the reason why eigen function is slow is that the matrix multiplication on Eigen lib is very slow on my VS2015

Do you have any idea about the reason?

**Comment by ardeal** [comment]
Hi Hi Patrikhuber,

Thanks any way!
I found out the reason of this issue:
we should enable O2 optimization on VS otherwise eigen functions run very slow.

**Comment by patrikhuber** [comment]
O2 should be enabled by default actually if you use the VS generator and do a Release build in VS. Glad you found out.
