### ISSUE TITLE
question: CPU time needed for hog feature in SDM code

### ISSUE THREAD

**Issue by ardeal** [patrikhuber/superviseddescent#43]
Hi Patrikhuber,

when we run the SDM test(predict) code, the CPU time needed for each image is so much. For different size of images, the time needed is much different.

My qestions are:
1) is there any way to optimize the time needed to calculate hog feature?
2) for different faces with different size, the CPU time needed is much different. can we resize the image to small size for hog calculation? will this method lead to the bad accuracy of SDM?

Many thanks for your answer!

**Comment by patrikhuber** [comment]
Hi,

Sure you can resize the image. You'd have to test the accuracy if you want to know. If you go through the issues list here, there's a few more tickets with some ideas to improve the speed. Alternatively you can reduce the feature size and retrain, or use different features if you're not happy with vlhog (though vlhog is pretty fast in my past experience). Also you can check the current literature.

**Comment by ardeal** [comment]
Thanks patrikhuber!
