### ISSUE TITLE
Confidence measure of landmark detection?

### ISSUE THREAD

**Issue by siddie** [patrikhuber/superviseddescent#44]
Hi Patrik!

Is there any way of measuring confidence in landmark detection? No ground truth data.
A naive approach I see so far is using facedetect rectangle area ratio to area of a bounding box around detected landmarks, but, are there better ways?

**Comment by patrikhuber** [comment]
Hi,

I'm not actively working on landmark detection. I think this has been asked before quite a few times here. If you go through the issue search you should find it - maybe start with #24 but I think there should be more.
Also I am sure there have been advances on this in the past 1-2 years which you will find in the literature (check CVPR etc.).

**Comment by patrikhuber** [comment]
Closing this since the GitHub issues are not really for such generic questions, but feel free to reply nonetheless.

Thanks!
