### ISSUE TITLE
Question: about pose estimation

### ISSUE THREAD

**Issue by ardeal** [patrikhuber/superviseddescent#45]
Hi Patrikhuber,

I would like to run pose estimation in your code. should I run the project under examples/pose_estimation or some other one?

Thanks!

**Comment by patrikhuber** [comment]
Well, have a look at the example code. It's modelled after the original SDM paper. You would have to train it and probably extend a bit. To be honest I would recommend doing pose estimation using a different method. If you've already got landmarks, try our [eos](github.com/patrikhuber/eos) 3D fitting library.

**Comment by ardeal** [comment]
Hi Patrikhuber,

I tried the pose_estimation project in your code. The speed is very good.
But I cannot understand the training procedure in pose_estimation.cpp file. you didn't even input any images for training. 

as I only need pose estimation functionality, I don't need other functionality which might need extra time of CPU.

I checked your eos code. eos code uses 3D model and 2D landmarks to project the pose. My question is how about the speed of the pose_estimation algorithms. how much time is needed to run it for one image on your platform?

**Comment by ardeal** [comment]
In my project, I will run face detection, SDM for landmark and then pose estimation. so I would like to run a very computation effective pose estimation algorithms which is based on SDM landmarks.
Do you think it is a good choice for me to use your pose estimation in SDM solution?

**Comment by patrikhuber** [comment]
As mentioned, have a look at how Xiong & De la Torre do the pose estimation using SDM in their paper - I think you'll have to train it using training data but don't recall the details currently.

eos can estimate the 3D pose from landmarks in the order of milliseconds. You can even get below 1ms if you just need a rough estimate.

**Comment by ardeal** [comment]
Got it. Thanks!
