### ISSUE TITLE
landmark detection.cpp trained result looks like mean shape.

### ISSUE THREAD

**Issue by codediner** [patrikhuber/superviseddescent#52]
Hi, 
   Patrik, thank you for your code of SDM, I have a problem when I use the landmark detection.cpp, I have used about 3000 images in the IBug for training in landmark detetion.cpp, but when I track the face using the trained model, il looks like the mean shape and when I close the eye, the landmark didn't follow, it keeps always the same form, I don't understand the reason.

  Waiting for your answer.

Yours sincerely
 Anto

**Comment by patrikhuber** [comment]
Hi Anto,

Apologies for the late reply, it's probably not relevant anymore. For landmark detection, I recommend the RCR in [apps/rcr](https://github.com/patrikhuber/superviseddescent/tree/master/apps/rcr).
The code in `landmark_detection.cpp` is rather thought for beginners or for people who want to understand the algorithm, e.g. while reading the paper. Or people that want to build upon it by themselves. RCR is built upon this code.
RCR and also the pretrained RCR model from [4dface](github.com/patrikhuber/4dface) work quite well for me and they definitely don't output mean landmarks :-)
Note that if your training data doesn't contain people with closed eyes (which I think the ibug images don't really), then obviously your trained detector will also not be able to know & follow closing eyes.

**Comment by patrikhuber** [comment]
I'm going to close this, as I don't think there is an issue with the superviseddescent library. Feel free to re-open otherwise.
