### ISSUE TITLE
68 landmark points pre-trained model

### ISSUE THREAD

**Issue by ghost** [patrikhuber/superviseddescent#54]
Hello Patrik,

Thanks for your amazing code first!

I have a question, where can I find the pre-trained 68 landmark points model? I just found 22 and 29 one.

Thanks

**Comment by patrikhuber** [comment]
Hi Runsheng, (sorry I'm not too familiar with Chinese names and do not know which of them is your first name ;-) )

You can find the model here: http://www.patrikhuber.ch/files/models/face_landmarks_model_rcr_68.bin :-)

Patrik

**Comment by ghost** [comment]
Hello Patrik,

You can call me Runsheng. Thanks a lot for your help!

Best,
Runsheng Xu

**Comment by patrikhuber** [comment]
Awesome! You're welcome Runsheng :-)

Best wishes,
Patrik
