### ISSUE TITLE
How can i get mean_ibug_lfpw_68.txt  in new dataset?

### ISSUE THREAD

**Issue by nj0904107027** [patrikhuber/superviseddescent#55]
thanks for your share code 。I use it in my project and train the model using my own dataset .But I dont konw how to  get  the mean file.

**Comment by patrikhuber** [comment]
Thanks, you're welcome.
Just use your dataset to compute the mean of all landmarks - that's pretty trivial. Otherwise, if you search through the issues, I think I may have linked the ibug mean file somewhere a couple of years ago.
