### ISSUE TITLE
Pre trained model for 2d landmarking tracking

### ISSUE THREAD

**Issue by eloi-loomai** [patrikhuber/superviseddescent#57]
Hi,

Can you please tell me if there is a pre trained model that I can download for 2d landmarks tracking?

Thanks for your work!

**Comment by patrikhuber** [comment]
Hi,

Thanks!

There's a couple pre-trained "toy" models in [`apps/rcr/data`](https://github.com/patrikhuber/superviseddescent/tree/master/apps/rcr/data). Then there's the one that the [patrikhuber/4dface](https://github.com/patrikhuber/4dface/blob/3106cad5741e61155473d4d0b9c2740f1f25735e/CMakeLists.txt#L94) demo app uses (the demo is a bit dated) - you'll find the download link if you click on that link, on that line in the CMakeLists. That model is pretty good and useful, but nonetheless I'm sure you're aware that it's around 2+ or so years old, and is probably not as good as 2018's models (also it wasn't trained using too many data-augmentation "tricks").
